[versions]
# Gradle not compactible with JVM 21 & Kotlin 2.0.0 for whatever reason so we will stick to 1.9.21 with Java 21 for now
#kotlin = "1.9.21"
kotlin = "2.1.20"
# https://ktor.io/docs/releases.html#release-details
# Soon bump to ver. 3.0.0
ktor = "3.1.2"
# https://logback.qos.ch/download.html
logback = "1.5.18"
stdx = "1.3.0"
# https://litote.org/kmongo/quick-start/ => DEPRECATED
# https://www.mongodb.com/developer/products/mongodb/getting-started-kotlin-driver/
mongodb = "4.10.1"
# https://github.com/oshai/kotlin-logging
klogger = "7.0.6"
# https://github.com/05nelsonm/kmp-process
kmp-process = "0.1.0-alpha03"
# https://www.slf4j.org/download.html
slf4j = "2.0.17"
# https://insert-koin.io/docs/setup/koin
koin = "4.0.3"
# MINA https://mvnrepository.com/artifact/org.apache.mina/mina-core/2.2.4
mina = "2.2.4"
mina-sshd = "2.15.0"

[libraries]
ktor-bom = { group = "io.ktor", name = "ktor-bom", version.ref = "ktor" }
ktor-server-cio = { group = "io.ktor", name = "ktor-server-cio" }
ktor-server-logging = { group = "io.ktor", name = "ktor-server-call-logging" }
ktor-server-statuspages = { group = "io.ktor", name = "ktor-server-status-pages" }
ktor-contentnegotiation-server = { group = "io.ktor", name = "ktor-server-content-negotiation" }
ktor-contentnegotiation-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json" }
ktor-auth-core = { group = "io.ktor", name = "ktor-server-auth" }
ktor-auth-jwt  = { group = "io.ktor", name = "ktor-server-auth-jwt" }

mina-core = { group = "org.apache.mina", name = "mina-core", version.ref = "mina" }
mina-sshd = { group = "org.apache.sshd", name = "sshd-core", version.ref = "mina-sshd" }
mina-sftp = { group = "org.apache.sshd", name = "sshd-sftp", version.ref = "mina-sshd" }

ktor-client-contentnegotiation = { group = "io.ktor", name = "ktor-client-content-negotiation" }

stdx-bom = { group = "dev.schlaubi", name = "stdx-bom", version.ref = "stdx" }
stdx-core = { group = "dev.schlaubi", name = "stdx-core" }
stdx-envconf = { group = "dev.schlaubi", name = "stdx-envconf" }
stdx-logging = { group = "dev.schlaubi", name = "stdx-logging" }
stdx-coroutines = { group = "dev.schlaubi", name = "stdx-coroutines" }

mongodb = { group = "org.mongodb", name = "mongodb-driver-kotlin-coroutine", version.ref = "mongodb" }
klogger = { group = "io.github.oshai", name = "kotlin-logging-jvm", version.ref = "klogger" }

slf4jSimple = { group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4j"}

ktor-server-testHost = { group = "io.ktor", name = "ktor-server-test-host" }
kotlinTest = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
kotlinSerialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version = "1.8.1" }

koin-bom = { group = "io.insert-koin", name = "koin-bom", version.ref = "koin" }
koin-ktor = { group = "io.insert-koin", name = "koin-ktor" }
koin-logging = { group = "io.insert-koin", name = "koin-logger-slf4j" }

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
buildConfig = { id = "com.github.gmazzo.buildconfig", version = "5.3.5" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }

# https://plugins.gradle.org/plugin/com.gradleup.shadow/8.3.6
shadow = { id = "com.gradleup.shadow", version = "8.3.6"}